41Taumatawiwi.Web/Controllers/BlogController.cs
using System.Web.Mvc;

namespace _41Taumatawiwi.Controllers
{
    public class BlogController : Controller
    {
        // GET: /<controller>/
        public ActionResult Index()
        {
            return View();
        }
    }
}

41Taumatawiwi.Web/Controllers/ContactController.cs
using System.Web.Mvc;

namespace _41Taumatawiwi.Controllers
{
    public class ContactController : Controller
    {
        // GET: /<controller>/
        public ActionResult Index()
        {
            return View();
        }
    }
}

41Taumatawiwi.Web/Controllers/FacilitiesController.cs
using System.Web.Mvc;

namespace _41Taumatawiwi.Controllers
{
    public class FacilitiesController : Controller
    {
        // GET: /<controller>/
        public ActionResult Index()
        {
            return View();
        }
    }
}

41Taumatawiwi.Web/Controllers/GalleryController.cs
using _41Taumatawiwi.Core.Repositories.Instagram;
using System.Web.Mvc;

namespace _41Taumatawiwi.Controllers
{
    public class GalleryController : Controller
    {
        // GET: /<controller>/
        public ActionResult Index()
        {
            var imageRepo = new InstagramPhotoRepository();

            var images = imageRepo.GetAll();

            return View(images);
        }
    }
}

41Taumatawiwi.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Wākainga Opononi</title>

    <!-- Bootstrap -->
    <link href="@Url.Content("css/bootstrap.min.css")" rel="stylesheet">

    <!-- Font Awesome CSS -->
    <link href="@Url.Content("css/font-awesome/font-awesome.min.css")" rel="stylesheet">

    <!-- Simple Line Icons -->
    <link href="@Url.Content("css/simple-line-icons/simple-line-icons.css")" rel="stylesheet">

    <!-- google font -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>

    <!-- owl-carousel -->
    <link href="@Url.Content("plugins/owl-carousel/owl.carousel.css")" rel="stylesheet">
    <link href="@Url.Content("plugins/owl-carousel/owl.theme.css")" rel="stylesheet">

    <!-- magnific-popup -->
    <link href="@Url.Content("plugins/magnific-popup/magnific-popup.css")" rel="stylesheet">

    <!-- animate -->
    <link href="@Url.Content("css/animate/animate.css")" rel="stylesheet">

    <!-- style -->
    <link href="@Url.Content("css/style.css")" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="slider-background">

    <!-- Preloader 	-->
    <div id="preloader">
        <div id="status">&nbsp;</div>
    </div>
    <!-- ./Preloader -->
    <!-- pattern -->
    <div id="bg_pattern"></div>
    <!-- ./pattern -->
    <!-- scrollToTop -->
    <a href="#" class="scrollToTop">
        <i class="fa fa-angle-up fa-2x"></i>
    </a>
    <!-- ./scrollToTop -->
    <!-- header -->
    <header id="header">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-navbar" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                        <img src="img/logo2.png" alt="logo">
                    </a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="collapse-navbar">

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="@Url.Action("Index", "Blog")" style="font-size:20px">Blog</a></li>
                        <li><a href="@Url.Action("Index", "Gallery")" style="font-size:20px">Gallery</a></li>
                        <!--<li><a href="@Url.Action("Index", "Facilities")">The Cabin</a></li>
                        <li><a href="@Url.Action("Index", "ThingsToDo")">Things to do</a></li>
                        <li><a href="@Url.Action("Index", "RatesBooking")">Rates &amp; Booking</a></li>
                        <li><a href="@Url.Action("Index", "Testimonials")">Testimonials</a></li>
                        <li><a href="@Url.Action("Index", "Contact")">Contact</a></li>-->
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container -->
        </nav>
    </header>
    <!-- ./header -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="@Url.Content("Scripts/jquery-1.11.3.min.js")"></script>
    <script src="@Url.Content("Scripts/bootstrap.min.js")"></script>

    <!-- smooth-scroll -->
    <script src="@Url.Content("plugins/smooth-scroll/smooth-scroll.js")"></script>

    <!-- backstretch -->
    <script src="@Url.Content("plugins/backstretch/backstretch.min.js")"></script>

    <!-- owl-carousel -->
    <script src="@Url.Content("plugins/owl-carousel/owl.carousel.js")"></script>

    <!-- wow -->
    <script src="@Url.Content("plugins/wow/wow.js")"></script>

    <!-- typed -->
    <script src="@Url.Content("plugins/typed/typed.min.js")"></script>

    <!-- magnific-popup -->
    <script src="@Url.Content("plugins/magnific-popup/jquery.magnific-popup.js")"></script>

    <!-- jqBootstrapValidation -->
    <script src="@Url.Content("plugins/jqBootstrapValidation/jqBootstrapValidation.js")"></script>

    @RenderBody()

    <!-- footer -->
    <footer id="footer">
        <div class="container">
            <ul class="list-inline">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google"></i></a></li>
            </ul>
            <div class="copyright">&copy; 2016 Fullscreen | <a href="http://www.Bootstrapwizard.info" target="_blank">Bootstrapwizard</a></div>
        </div>
    </footer>
    <!-- ./footer -->

    <!-- main js -->
    <script src="@Url.Content("Scripts/main.js")"></script>

</body>
</html>